### ISSUE TITLE
您好，请问方便提供一下项目运行的环境要求吗

### ISSUE THREAD

**Issue by Yishier** [HourunLi/CCKS2022#1]

**Comment by HourunLi** [comment]
oh 才看到消息不好意思。我当时是在conda虚拟环境下弄的，torch cuda版本貌似有个对应关系，然后直接创建对应的虚拟环境就好，还挺简单的。不过我当时打完这个比赛就删除了虚拟环境了 所以也记不住版本了。没有在 报告里写出来很抱歉
